platform :ios, '9.0'

target 'Pai-Example' do
  use_frameworks!

  pod 'Pai', :path => '../'

  target 'Pai-ExampleTests' do
    inherit! :search_paths
  end

  target 'Pai-ExampleUITests' do
    inherit! :search_paths
  end
end
